### ISSUE TITLE
Cannot run tests

### ISSUE THREAD

**Issue by harshpreet93** [timshannon/badgerhold#14]
I'm trying to run the tests and getting the following error:
` # github.com/timshannon/badgerhold
./store.go:48:41: cannot call non-function badger.DefaultOptions (type badger.Options)
FAIL	github.com/timshannon/badgerhold [build failed]`

Am I doing something wrong here?

**Comment by timshannon** [comment]
I know at one point, dgraph updated their default options interface, and broke backwards compatibility.  See https://github.com/timshannon/badgerhold/issues/12.  I updated to their latest, and changed the code to reflect their changes.

I'm betting you might still have an older version of badger installed.  Try running `go get -u` and trying again.

**Comment by harshpreet93** [comment]
@timshannon that was the issue! 🙇Closing this now
