### ISSUE TITLE
StartsWith operator

### ISSUE THREAD

**Issue by nkev** [timshannon/badgerhold#3]
This is fantastic Tim, let me be the first to congratulate you!
I'd love to make some contributions too if you'll consider them.
The first thing that comes to mind are `StartsWith` and `EndsWith` operators for string fields.
I think they would be useful for multi-segmented keys and indexes:

```Go
store.Find(badgerhold.Where(badgerhold.Key).StartsWith("en-AU:")
```

I know we can probably already do this using `Regex` or `MatchFunc` but it looks more readable with the above syntax.

**Comment by timshannon** [comment]
Simpler, Clearer, and probably faster than Regex.  Sounds worth it to me.

**Comment by nkev** [comment]
I'll try to get a pull request to you soon.

**Comment by nkev** [comment]
I just started a major new project and won't have time to implement this any time soon, unfortunately.
