### ISSUE TITLE
No ID Returned in Get

### ISSUE THREAD

**Issue by Wolveix** [timshannon/badgerhold#30]
I'm not sure if I'm missing something, but it seems like `.Get` doesn't return the ID within the struct that gets returned. I tested the same with [BoltHold](https://github.com/timshannon/bolthold), which produced exactly what I was expecting, so I suspect that this is a bug with BadgerHold. If you run the [linked code example](https://pastebin.com/Uh06zvpd), you'll get the following response:

> Testing badger...
> {johnsmith@domain.tld 0}
> {johnsmith2@domain.tld 1}
> [{johnsmith2@domain.tld 1}]
> {johnsmith2@domain.tld 0} < Should be 1
> Testing bolt...
> {johnsmith@domain.tld 1}
> {johnsmith2@domain.tld 2}
> [{johnsmith2@domain.tld 2}]
> {johnsmith@domain.tld 2}

Badger example:

```Go
type User struct {
	Email    string `badgerhold:"index"`
	ID       uint64 `badgerhold:"key"`
}
```
```Go
user := User{
    Email:    "johnsmith@domain.tld",
}

if err := s.Insert(badgerhold.NextSequence(), &user); err != nil {
    log.Fatal(err)
}

fmt.Println(user)
// OUTPUT: &{johnsmith@domain.tld 0} CORRECT
```

```Go
user2 := User{
    Email:    "johnsmith2@domain.tld",
}

if err := s.Insert(badgerhold.NextSequence(), &user2); err != nil {
    log.Fatal(err)
}

fmt.Println(user2)
// OUTPUT: &{johnsmith2@domain.tld 1} CORRECT
```

```Go
var userResults []User

if err := s.Find(&userResults, badgerhold.Where("Email").Eq("johnsmith2@domain.tld").Index("Email")); err != nil {
    log.Fatal(err)
}

fmt.Println(userResults)
// OUTPUT: [{johnsmith2@domain.tld 1}] CORRECT
```

```Go
var userReturned User

if err := s.Get(uint64(1), &userReturned); err != nil {
    log.Fatal(err)
}

fmt.Println(userReturned)
// OUTPUT: &{johnsmith@domain.tld 0} INCORRECT
// EXPECTED: &{johnsmith@domain.tld 1}
```

**Comment by timshannon** [comment]
Should be fixed in master now.

**Comment by Wolveix** [comment]
Nice one, thanks! :D
