### ISSUE TITLE
Load multiple by primary key

### ISSUE THREAD

**Issue by ivanjaros** [timshannon/badgerhold#35]
Since objects are stored by the key that is provided to the crud methods via argument, they do not need to be declared as indices, except "key" which will provided auto-incrementing uin64 index, if needed. I have string primary keys(uuid) so how do I use the Find() method to load multiple objects by their ids? I do not see any method for the query. Do I need to define the index or how does it work?

**Comment by timshannon** [comment]
Unless I misunderstanding what you're asking, you simple need to use the `badgerhold.Key` const:

From the README: 

![image](https://user-images.githubusercontent.com/1330485/92750144-6a050780-f34c-11ea-8383-0742e2aadd8c.png)

**Comment by timshannon** [comment]
You can also use `badgerhold.Where(badgerhold.Key).In(1,2,3,4,5)`
