### ISSUE TITLE
Support for other backends?

### ISSUE THREAD

**Issue by ivanjaros** [timshannon/badgerhold#40]
It looks like "they" made badger completely unusable on Windows and I am in a need of fast db so bolt won't work for me(it has blocking transactions). So I was wondering if the *hold could be made into a wrapper that could take different backends, like bitcask or pebble?

**Comment by timshannon** [comment]
I can't see this project, which is targeted specifically at Badger, supporting multiple backends.  However, that doesn't mean I may not create a separate project that does this, as it's something I've tossed around doing for a while now.

If I do take on something like that, I'll be sure to update this issue.
