### ISSUE TITLE
Support for ForEach?

### ISSUE THREAD

**Issue by omz13** [timshannon/badgerhold#47]
I'm looking to migrate from [bolthold](https://github.com/timshannon/bolthold) to badgerhold... one thing that seems to be missing (unless I am overlooking something) that I use quite a lot is [ForEach](https://github.com/timshannon/bolthold#foreach)? Are you planning to add this?

**Comment by timshannon** [comment]
It should be a quick port over from Bolthold.  I'll get started on it soon.

**Comment by timshannon** [comment]
Added ForEach and Count on the master branch.  Open up a new issue if you run into any problems.

Thanks,
