### ISSUE TITLE
Unique constraints

### ISSUE THREAD

**Issue by brianhiss** [timshannon/badgerhold#5]
@timshannon,

I enjoyed reading your article comparing boltdb-vs-badger. I've been flopping back and forth between the two of them, balancing the pros and cons of each.

That being said, I've been playing around with badgerhold. I wanted to know if you support anything like Storm, unique constraints on a field within a struct?

```go
type User struct {
  ThePrimaryKey string `storm:"id"`// primary key
  Group string `storm:"index"` // this field will be indexed
  Email string `storm:"unique"` // this field will be indexed with a unique constraint
  Name string // this field will not be indexed
}
```

If not, is this something you'd consider? Doesn't seem like bolthold supports that use case either, but I've only skimmed through it and haven't used it extensively.

Thanks again for all your contributions, code and research.

**Comment by timshannon** [comment]
Not currently supported, but it's a great idea. I'll start working on it
when I get a chance.

**Comment by timshannon** [comment]
PR #7 Adds unique constraint support.  All of my tests are passing, but if you run into any issues with it, because to open up an issue.

Thanks,

**Comment by brianhiss** [comment]
@timshannon, that was fast! 

How do you use this, don't see anything in the docs yet? Something like: 
```
`badgerhold:"unique"`
```

**Comment by timshannon** [comment]
Well shoot, I knew I forgot something.

Yeah that's exactly what you do.  I'll update the README.

Thanks,

**Comment by timshannon** [comment]
README updated, thanks for the heads up.

**Comment by brianhiss** [comment]
Looks good, thanks! Will make it a lot more powerful for some interesting use cases.
