### ISSUE TITLE
Ability to ignore struct properties

### ISSUE THREAD

**Issue by DirtyCajunRice** [timshannon/badgerhold#50]
It would be super helpful to be able to ignore properties with a tag similar to how json/yaml/glob etc do it. 
```go
type Example struct {
    Name string
    RuntimeInfo RuntimeInfo `badgerhold:"-"`
}
```

**Comment by timshannon** [comment]
You can!  But you need to use the proper tag for whatever encoding you are using with Badgerhold. The default uses GOB encoding, but you can use JSON and use JSON tags.

```go
type Example struct {
    Name string
    RuntimeInfo RuntimeInfo `json:"-"`
}
```

Alternately you can also just make them non-exported by starting the field name with a lower case letter.
