### ISSUE TITLE
Support bolthold-like Contains / ContainsAny / ContainsAll ?

### ISSUE THREAD

**Issue by omz13** [timshannon/badgerhold#53]
I'm moving another bit of code that I wrote to use badgerhold instead of bolthold... and I'm a bit stuck because it looks like badgerhold does not implement the Contains / ContainsAny / ContainsAll queries.... can these be moved over?

**Comment by timshannon** [comment]
Yeah it can be done pretty quickly as soon as I get a chance.

**Comment by omz13** [comment]
As a quick workaround for myself I've replaced my use of Contains with some MatchFunc... but Contains is always handy to have because it makes prototyping a bit easier before writing custom MatchFuncs.

**Comment by timshannon** [comment]
This is now supported in master.

Thanks,
