### ISSUE TITLE
Skip() and Limit() without Where clause

### ISSUE THREAD

**Issue by kajjagtenberg** [timshannon/badgerhold#64]
Is there a way to get all records of a type and specifying a Skip and a Limit on the query, without having to specify a Where clause?

Or maybe it is possible to add an All() query which keeps all records elligible for retrieval?

Thanks in advance.

**Comment by timshannon** [comment]
Any empty query matches against all records:

```go
q := &badgerhold.Query{}

err := store.Find(&result, q.Skip(10).Limit(50))
```

**Comment by kajjagtenberg** [comment]
Thanks!
