### ISSUE TITLE
Custom index name error

### ISSUE THREAD

**Issue by Ale1ster** [timshannon/badgerhold#71]
When a struct has an index defined on a field whose name does not match the field name, the specified index name is not respected:
```golang
type Person struct {
	Name string
	Division string `badgerholdIndex:"IdxDivision"`
}
```
In the above struct, the query 
```golang
badgerhold.Where("Division").Eq("sales").Index("IdxDivision")
```
fails with the error `The index IdxDivision does not exist`, while the query
```golang
badgerhold.Where("Division").Eq("sales").Index("Division")
```
is executed successfully.

This behaviour is observed against tag `v1.0.0` (commit hash `8addb9d`), but the same should be observed in `v3.0.0` (`2b6764d`) tag as well.

**Comment by timshannon** [comment]
Originally all the query methods referenced field names, but it clearly states `indexName` in my documentation 🤦‍♂️, that's a complete oversight.

Thanks for the report.  I'll fix this on the V3 branch, as well as new V4 version on master that will contain some other backward incompatible changes.

**Comment by timshannon** [comment]
This should be good now with both v3 and v4 (master).

Thanks
